---
title: "Geographic info MX"
author: "Shankar K Shakya"
date: "December 29, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
location <- read.csv("Dgeo_MX.csv", header = TRUE)

library(ggmap)


mapImage <- qmplot(Longitude, Latitude, data = location, colour = I('red'), size = I(3), darken = .3)



geocode("Mexico")

qmplot(geocode("Mexico"))

qmplot()

mx <- get_map(location = "Mexico", zoom = 6)

mymap <- ggmap(mx) + geom_point(data = location, aes(x = Longitude, y = Latitude), size = 3, color = "red")

mymap



```



```{r}
library(maptools)

mx <- readShapePoly("mexstates/mexstates.shp")
class(mx)

head(mx@data)
spplot(mx, "ADMIN_NAME")

new <- mx[mx@data$ADMIN_NAME == "Mexico", ]
plot(new)
class(new)

new <- mx[grep("Mexico|Tlaxcala|Michoacan", mx@data$ADMIN_NAME),]
plot(new)



spplot(new , zcol = "GMI_ADMIN")






sub <- fortify(mx)
head(sub)

class(sub)

df <- mx@data


mx@data$GMI_ADMIN == "Michoacan"





```







```{r}













```




