---
title: "P infestans SSR 2015/16 MX"
author: "Shankar K Shakya"
date: "December 19, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}

rm(list = ls())
library(poppr)

P.inf <- read.genalex("all_2015_mx.csv", ploidy = 4)
P.inf

P.inf <- missingno(P.inf, type = "loci", cutoff = 0.05)
P.inf

ploidy_tab <- info_table(P.inf, type = "ploidy")

mat_sum <- rowSums(ploidy_tab > 2, na.rm = TRUE)

diploid_pinf <- P.inf[mat_sum == 0]
diploid_pinf

##recoding the ploidy

diploid_pinf <- recode_polyploids(diploid_pinf, newploidy = 2)

#mlg.table(diploid_pinf)


# Corrected simpson diversity index
uSimp <- function(x){
  lambda <- vegan::diversity(x, "simpson")
  x <- drop(as.matrix(x))
  if (length(dim(x)) > 1){
    N <- rowSums(x)
  } else {
    N <- sum(x)
  }
  return((N/(N-1))*lambda)
}

unbiased <- poppr(diploid_pinf, uSimp = uSimp)

#write.csv(unbiased, "summary_by_pop.csv", quote = FALSE)


```



###### TEST FOR LINKAGE DISEQUILIBRIUM

```{r}


ia_Pinf <- poppr(diploid_pinf, clonecorrect = TRUE, strata = ~Pop, sample = 999)
ia_Pinf
#write.csv(ia_Pinf, "ia_Pinf.csv")
# ia_Pinf <- last_plot()
# 
# ia_Pinf <- ia_Pinf + theme(text = element_text(size = rel(5))) +
#   labs(title = "Standardized index of association") + 
#   theme(plot.title = element_text(size = 35))
# 
# ia_Pinf


diploid_pinf_no_sangeronimo2016 <- popsub(diploid_pinf, blacklist = "San Ger贸nimo_2016")
poppr(diploid_pinf_no_sangeronimo2016, clonecorrect = TRUE, strata = ~Pop, sample = 999)


```

## HWE for diploid only
```{r}

library(pegas)

hwe_per_pop <- seppop(diploid_pinf) %>% lapply(hw.test, B = 0)
per_pop_mat <- sapply(hwe_per_pop, "[", i = TRUE, j = 3)
alpha <- 0.05
per_pop_mat[per_pop_mat > alpha] <- 1

library(lattice)


hwe_plot <- levelplot(per_pop_mat, xlab = "Locus", ylab = "Population")
hwe_plot


```


## allelic richness

```{r}

# library(strataG)
# diploid_pinf.gtypes <- genind2gtypes(clonecorrect(diploid_pinf))
# allelicRichness(diploid_pinf.gtypes)
# summarizeLoci(diploid_pinf.gtypes)

library(PopGenReport)
allleic_rich <- allel.rich(diploid_pinf)

allelic_richness <- allleic_rich$all.richness
allelic_richness <- as.data.frame(apply(richness, MARGIN = 2, mean))
colnames(allelic_richness) <- "Allelic richness"


sum_richness.df <- as.data.frame(allleic_rich$sum.richness)
colnames(sum_richness.df) <- "Sum richness"

allelic_summary <- cbind(allelic_richness, sum_richness.df)

# ggplot(data = allelic_summary, aes(x = rownames(allelic_richness.df), y = "Sum richness")) + 
#   geom_bar(stat = 'identity')











#Allelic diversity for each locus and each population
locus_table(diploid_pinf, pop = "Michoacan_2001_2010")
locus_table(cc_P.inf, pop = "San Ger贸nimo")
locus_table(cc_P.inf, pop = "Juchitepec")
locus_table(cc_P.inf, pop = "Toluca")
locus_table(cc_P.inf, pop = "Tlaxcala")


```



## STRUCTURE

```{r}

Sys.setenv(PATH = paste("C:/Program Files (x86)/Structure2.3.4/bin", Sys.getenv("PATH"), sep = ";"))

Sys.setenv(PATH = paste("C:/Users/Shankar/Downloads/CLUMPP_Windows.1.1.2/", Sys.getenv("PATH"), sep = ";"))

diploid_pinf_cc <- clonecorrect(diploid_pinf)

library(strataG)

sr <- structureRun(genind2gtypes(diploid_pinf), k.range  = 1:8, burnin = 20000, num.k.rep = 10, noadmix = FALSE, numreps = 100000)

#save(sr, file = "diploid_pinf_str.RData")

evno <- evanno(sr, plot = T)

qmat2 <- clumpp(sr, k = 2, sim.stat = "g.prime", repeats = 10000)

t <- structurePlot(qmat2, col = c("orange", "blue"))

t <-   t + theme_minimal() +  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
    theme(axis.text = element_text(size =12))
    
  
t


# x <- load("structure_except_chapingo.RData")
# y <- get(x)
# evno <- evanno(sr, plot = T)
# qmat2 <- clumpp(sr, k = 2, sim.stat = "g.prime", repeats = 10000)
# structurePlot(qmat2)


```


## AMOVA
```{r}
amv <- poppr.amova(diploid_pinf, 
                   hier = ~Pop, 
                   clonecorrect = TRUE, 
                   dist = NULL)

amv


set.seed(15)
y <- randtest(amv, nrepet = 999)
class(y)
plot(y)

```


## Population structure test

```{r}

diploid_pinf_no_sangeronimo2016 <- popsub(diploid_pinf, blacklist = "San Ger贸nimo_2016")

diploid_pinf_no_sangeronimo2016

pairwise_gst <- pairwiseTest(genind2gtypes(clonecorrect(diploid_pinf_no_sangeronimo2016)), stats = "gst", nrep = 10000)

gst_mat <- pairwise_gst$pair.mat$Gst

gst_mat[upper.tri(gst_mat)] <- NA

fst_mat <- as.dist(gst_mat)

geodist <- read.table("geo.txt")
geodist_mat <- as.dist(geodist)

ibd <- mantel.randtest(fst_mat, geodist_mat)
plot(ibd)

library(MASS)
dens <- kde2d(fst_mat, geodist_mat n=300)
myPal <- colorRampPalette(c("white","blue","gold", "orange", "red"))
plot(Dgeo, Dgen, pch=20,cex=.5)
image(dens, col=transp(myPal(300),.7), add=TRUE)
abline(lm(Dgen~Dgeo))
title("Isolation by distance plot")

```


### Pairwise GST values without San Geronimo 2016
```{r}

diploid_pinf_no_sangeronimo2016 <- popsub(diploid_pinf, blacklist = "San Ger贸nimo_2016")

diploid_pinf_no_sangeronimo2016

pairwise_gst <- pairwiseTest(genind2gtypes(clonecorrect(diploid_pinf_no_sangeronimo2016)), stats = "gst", nrep = 10000)

#write.csv(pairwise_gst$pair.mat, "Pairwise GST except sangeronimo2016.csv")

gst_mat <- pairwise_gst$pair.mat$Gst
gst_mat[upper.tri(gst_mat)] <- t(gst_mat)[upper.tri(gst_mat)]

gst_mat[is.na(gst_mat)] <- 0

library(reshape2)
gst_mat[upper.tri(gst_mat)] <- NA
lower_tri <- melt(gst_mat, na.rm = TRUE)

ggheatmap <- ggplot(lower_tri, aes(x = Var1, y = Var2, fill = value)) + geom_tile(color = "white") + 
  scale_fill_gradient(low = "green", high = "red" , space = "Lab", name="Pairwise GST") + theme_minimal() + 
   theme(axis.text.x = element_text(angle = 90, vjust = 1, size = 12, hjust = 1)) + coord_fixed() +
  labs(x = "Population", y = "Population") +
  theme(axis.text.y = element_text(size = 12)) +
  theme(axis.title = element_text(size = 12))

ggheatmap


```




```{r}

# repeat_length <- c(2, 2, 2, 3, 3, 2, 2, 2, 2, 2, 2)
# dist_mat <- bruvo.dist(diploid_pinf, replen = repeat_length)
# tree_nj <- bruvo.boot(diploid_pinf, replen = repeat_length, 
#                       sample = 1000, cutoff = 70, tree = "nj")



```

## Discriminant Analysis of Principal Components

```{r}

set.seed(999)
P.infx <- xvalDapc(tab(diploid_pinf, NA.method = "mean"), pop(diploid_pinf))
P.infx


set.seed(999)
P.infx <- xvalDapc(tab(diploid_pinf, NA.method = "mean"), pop(diploid_pinf),
                   n.pca = 30:40,  n.rep = 100, 
                   parallel = "multicore", ncpus = 4L)


library(RColorBrewer)

myCol <- brewer.pal(nPop(diploid_pinf), "Paired") %>% setNames(popNames(diploid_pinf))

scatter(P.infx$DAPC, col=myCol, clabel = 0.75, pch=15:18, scree.pca = TRUE, scree.da = FALSE, 
        posi.pca = "bottomright", posi.leg = NULL, legend = TRUE, 
        cleg = 0.9, inset.solid = 1, xax = 1, yax = 2, cex.lab = 1, cex = 1.5, solid = 1, cstar = 0)


# ggcompoplot(P.infx$DAPC, diploid_pinf, pal = myCol) +
#   theme(axis.text.x = element_blank()) +
#   labs(title = "compo plot") +
#   theme(plot.title = element_text(size = 45 )) +
#   theme(legend.text = element_text(size = 20)) +
#   theme(legend.title = element_text(size = 23)) +
#   theme(axis.text.y = element_text(size = 12, face = "bold")) +
#   theme(axis.title.x = element_text(size = 18, face = "bold")) +
#   theme(axis.title.y = element_text(size = 18, face = "bold"))
#   

```



## Minimum Spanning Network


```{r}

diploid_pinf
diploid_pinf_cc <- clonecorrect(diploid_pinf)

min_span_net <- bruvo.msn(diploid_pinf_cc, replen = c(2, 2, 2, 3, 3, 2, 2, 2, 2, 2, 2), add = TRUE, loss = TRUE, showplot = FALSE, include.ties = TRUE)

set.seed(999)
plot_poppr_msn(diploid_pinf_cc,
               min_span_net,
               inds = "NONE",
               mlg = FALSE,
               gadj = 9,
               nodebase = 1.15,
               palette = rainbow,
               cutoff = NULL,
               quantiles = FALSE,
               beforecut = TRUE,
               layfun = igraph::layout.auto)



```


## Hexp vs altitude
```{r}

alt_data <- read.csv("GST_altitude.csv")
class(alt_data)

ggplot(data = alt_data, aes(x = Altitude, y = Hexp)) + geom_point()

ln_reg <- lm(Hexp ~ Altitude, data = alt_data)
summary(ln_reg)


```











