---
title: "STRATA"
author: "Shankar K Shakya"
date: "January 13, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}

rm(list = ls())
library(poppr)

#P.inf <- read.genalex("all_2015_2016_mx.csv", ploidy = 4)
P.inf <- read.genalex("new.csv", ploidy = 4)
P.inf

# splitStrata(P.inf) <- ~Region/Year
#setPop(P.inf) <- ~Region
# P.inf

ploidy_tab <- info_table(P.inf, type = "ploidy", plot = TRUE)
mat_sum <- rowSums(ploidy_tab > 2, na.rm = TRUE)

diploid_pinf <- P.inf[mat_sum == 0]
diploid_pinf

diploid_pinf <- recode_polyploids(diploid_pinf, newploidy = 2)

diploid_pinf <- missingno(diploid_pinf, type = "loci", cutoff = 0.05)
splitStrata(diploid_pinf) <- ~Region/Year
setPop(diploid_pinf) <- ~Region



# Corrected simpson diversity index
uSimp <- function(x){
  lambda <- vegan::diversity(x, "simpson")
  x <- drop(as.matrix(x))
  if (length(dim(x)) > 1){
    N <- rowSums(x)
  } else {
    N <- sum(x)
  }
  return((N/(N-1))*lambda)
}



unbiased <- poppr(diploid_pinf, uSimp = uSimp)
#write.csv(unbiased, "del.csv", quote = FALSE)

library(ggplot2)
ggplot(data = unbiased, aes(x = Pop, y = Hexp)) + geom_bar(stat = "identity")





p3 <- popsub(P.inf, sublist = c("Michoacan_2001/2008", "Toluca_1997" , "Tlaxcala_2007"))

info_table(p3, type = "ploidy", plot = TRUE)



```



###### TEST FOR LINKAGE DISEQUILIBRIUM

```{r}


ia_Pinf <- poppr(diploid_pinf, clonecorrect = TRUE, strata = ~Region, sample = 999, quiet = TRUE)
ia_Pinf
#write.csv(ia_Pinf, "del.csv")
# ia_Pinf <- last_plot()
# 
# ia_Pinf <- ia_Pinf + theme(text = element_text(size = rel(5))) +
#   labs(title = "Standardized index of association") + 
#   theme(plot.title = element_text(size = 35))
# 
# ia_Pinf




```

## HWE for diploid only
```{r}

library(pegas)

diploid_pinf_cc <- clonecorrect(diploid_pinf)
hwe_per_pop <- seppop(diploid_pinf_cc) %>% lapply(hw.test, B = 1000)
per_pop_mat <- sapply(hwe_per_pop, "[", i = TRUE, j = 3)
alpha <- 0.05
per_pop_mat[per_pop_mat > alpha] <- 1

library(lattice)


hwe_plot <- levelplot(per_pop_mat, xlab = "Locus", ylab = "Population")
hwe_plot


#Inbreeding Coefficient


library(pegas)
source("FIS.R")

fis(diploid_pinf)

boot.ppfis(diploid_pinf)

```


## allelic richness

```{r}

# library(strataG)
# diploid_pinf.gtypes <- genind2gtypes(clonecorrect(diploid_pinf))
# allelicRichness(diploid_pinf.gtypes)
# summarizeLoci(diploid_pinf.gtypes)

library(PopGenReport)
allleic_rich <- allel.rich(diploid_pinf)

allelic_richness <- allleic_rich$all.richness
allelic_richness <- as.data.frame(apply(allelic_richness, MARGIN = 2, mean))
colnames(allelic_richness) <- "Allelic richness"


sum_richness.df <- as.data.frame(allleic_rich$sum.richness)
colnames(sum_richness.df) <- "Sum richness"

allelic_summary <- cbind(allelic_richness, sum_richness.df)
pri_alleles <- private_alleles(diploid_pinf)
rowSums(pri_alleles > 0 )

library(ggplot2)
ggplot(allelic_summary, aes(rownames(allelic_summary), allelic_summary$`Sum richness`)) + geom_bar(stat = "identity") 



#Allelic diversity for each locus and each population
locus_table(diploid_pinf, pop = "Michoacan_2001/2010")
locus_table(cc_P.inf, pop = "San Gerónimo")
locus_table(cc_P.inf, pop = "Juchitepec")
locus_table(cc_P.inf, pop = "Toluca")
locus_table(cc_P.inf, pop = "Tlaxcala")

locus_table(diploid_pinf)


```



## STRUCTURE

```{r}

Sys.setenv(PATH = paste("C:/Program Files (x86)/Structure2.3.4/bin", Sys.getenv("PATH"), sep = ";"))

Sys.setenv(PATH = paste("C:/Users/Shankar/Downloads/CLUMPP_Windows.1.1.2/", Sys.getenv("PATH"), sep = ";"))


library(strataG)

gen2gtype <- function (x) {
  
  gen.mat <- genind2df(x, usepop = TRUE, oneColPerAll = TRUE)
  strata <- x@strata
  rownames(strata) <- rownames(gen.mat)
  x@strata <- strata
  gen.mat[gen.mat == "NA"] <- NA
  has.pop <- !is.null(x@pop)
  df2gtypes(x = gen.mat, ploidy = x@ploidy[1], id.col = NULL, 
            strata.col = if (has.pop) 
              1
            else NULL, loc.col = if (has.pop) 
              2
            else 1, 
            schemes = x@strata,  other = other(x))
}

diploid_pinf.g <- gen2gtype(diploid_pinf)
sr <- structureRun(diploid_pinf.g, k.range  = 1:5, burnin = 20000, num.k.rep = 10, noadmix = TRUE, numreps = 100000)

#save(sr, file = "noadmix_byregion_10SSR_no_chapingo.RData")

evno <- evanno(sr, plot = T)

qmat2 <- clumpp(sr, k = 3, sim.stat = "g.prime", repeats = 10000)

t <- structurePlot(qmat2, col = c("orange", "blue"))

t <-   t + theme_minimal() +  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
    theme(axis.text = element_text(size =12))
    
  
t


x <- load("admixture_diploid_pinf_by_region.RData")
sr <- get(x)

evno <- evanno(sr, plot = T)

qmat2 <- clumpp(sr, k = 2, sim.stat = "g.prime", repeats = 10000)
qmat3 <- clumpp(sr, k = 3, sim.stat = "g.prime", repeats = 10000)
qmat4 <- clumpp(sr, k = 4, sim.stat = "g.prime", repeats = 10000)
qmat5 <- clumpp(sr, k = 5, sim.stat = "g.prime", repeats = 10000)

qmat_list <- list(qmat2, qmat3, qmat4, qmat5)

for (k in 1:length(qmat_list)){
  temp <- qmat_list[[k]]
  temp$orig.pop <- factor(temp$orig.pop, levels = unique(temp$orig.pop)[c(6,4,1,3,2,5)], ordered = TRUE)
  qmat_list[[k]] <- temp
  
}

plots <- lapply(qmat_list, structurePlot, horiz = F)
library(cowplot)
plot_grid(plotlist = plots, nrow = 4, ncol = 1) +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) 


# t1 <- structurePlot(qmat2,  horiz = F)
# t2 <- structurePlot(qmat3,  horiz = F)
# t3 <- structurePlot(qmat4,  horiz = F)
# t4 <- structurePlot(qmat5,  horiz = F)
# 
# library(cowplot)
# final <- plot_grid(t1, t2, t3, t4, nrow = 4, ncol = 1)
# 
# final +  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
#   theme(axis.title.y = element_blank()) 
#   

```


## AMOVA
```{r}

repeat_length <- c(2, 2, 3, 3, 2, 2, 2, 2, 2, 2)
bruvodist <- bruvo.dist(clonecorrect(diploid_pinf), replen = repeat_length)

amv <- poppr.amova(diploid_pinf, 
                   hier = ~Region, 
                   clonecorrect = TRUE, 
                   dist = bruvodist,
                   within = F)

amv


set.seed(15)
y <- randtest(amv, nrepet = 999)
class(y)
plot(y)


library(mmod)
diploid_pinf_dist <- dist(genclone2genind(diploid_pinf))
strata <- strata(diploid_pinf)


pegas::amova(diploid_pinf_dist ~ Region, data = strata(genclone2genind(diploid_pinf)), nperm = 100)




```


## Population structure test

```{r}

pairwise_gst <- pairwiseTest(diploid_pinf.g, stats = "gst", nrep = 10000)

gst_mat <- pairwise_gst$pair.mat$Gst

gst_mat[upper.tri(gst_mat)] <- NA

fst_mat <- as.dist(gst_mat)

geodist <- read.table("geo.txt")
geodist_mat <- as.dist(geodist)

ibd <- mantel.randtest(fst_mat, geodist_mat)
plot(ibd)

library(MASS)
dens <- kde2d(fst_mat, geodist_mat n=300)
myPal <- colorRampPalette(c("white","blue","gold", "orange", "red"))
plot(Dgeo, Dgen, pch=20,cex=.5)
image(dens, col=transp(myPal(300),.7), add=TRUE)
abline(lm(Dgen~Dgeo))
title("Isolation by distance plot")

```


### Pairwise FST values
```{r}

diploid_pinf_cc <- clonecorrect(diploid_pinf)
diploid_pinf_cc.g <- gen2gtype(diploid_pinf_cc)

pairwise_fst <- pairwiseTest(diploid_pinf_cc.g, stats = "fst", nrep = 10000)

fst_mat <- pairwise_fst$pair.mat$Fst
fst_mat[upper.tri(fst_mat)] <- t(fst_mat)[upper.tri(fst_mat)]

fst_mat[is.na(fst_mat)] <- 0

library(reshape2)
fst_mat[upper.tri(fst_mat)] <- NA
lower_tri <- melt(fst_mat, na.rm = TRUE)

library(ggplot2)
ggheatmap <- ggplot(lower_tri, aes(x = Var1, y = Var2, fill = value)) + geom_tile(color = "white") + 
  scale_fill_gradient(low = "green", high = "red" , space = "Lab", name="Pairwise FST") + theme_minimal() + 
   theme(axis.text.x = element_text(angle = 90, vjust = 1, size = 12, hjust = 1)) + coord_fixed() +
  labs(x = "Population", y = "Population") +
  theme(axis.text.y = element_text(size = 12)) +
  theme(axis.title = element_text(size = 12))

ggheatmap


```



## Neighbor joining tree
```{r}

repeat_length <- c(2, 2, 2, 3, 3, 2, 2, 2, 2, 2, 2)
dist_mat <- bruvo.dist(diploid_pinf, replen = repeat_length)
# tree_nj <- bruvo.boot(diploid_pinf, replen = repeat_length, 
#                       sample = 1000, cutoff = 70, tree = "nj")



```

## Discriminant Analysis of Principal Components

```{r}

set.seed(999)
P.infx <- xvalDapc(tab(diploid_pinf, NA.method = "mean"), pop(diploid_pinf))
P.infx


diploid_pinf_cc <- clonecorrect(diploid_pinf)


set.seed(999)
P.infx <- xvalDapc(tab(diploid_pinf, NA.method = "mean"), pop(diploid_pinf),
                   n.pca = 40:50,  n.rep = 100, 
                   parallel = "multicore", ncpus = 4L)


library(RColorBrewer)

myCol <- brewer.pal(nPop(diploid_pinf), "Dark2") %>% setNames(popNames(diploid_pinf))

scatter(P.infx$DAPC, col=myCol, clabel = 0.75, pch=15:19, scree.pca = TRUE, scree.da = FALSE, 
        posi.pca = "bottomright", posi.leg = "topright", legend = TRUE, 
        cleg = 0.9, inset.solid = 1, xax = 1, yax = 2, cex.lab = 1, cex = 1.5, solid = 1, cstar = 0)


# ggcompoplot(P.infx$DAPC, diploid_pinf, pal = myCol) +
#   theme(axis.text.x = element_blank()) +
#   labs(title = "compo plot") +
#   theme(plot.title = element_text(size = 45 )) +
#   theme(legend.text = element_text(size = 20)) +
#   theme(legend.title = element_text(size = 23)) +
#   theme(axis.text.y = element_text(size = 12, face = "bold")) +
#   theme(axis.title.x = element_text(size = 18, face = "bold")) +
#   theme(axis.title.y = element_text(size = 18, face = "bold"))
#   

```



## Minimum Spanning Network


```{r}

diploid_pinf
diploid_pinf_cc <- clonecorrect(diploid_pinf)

min_span_net <- bruvo.msn(diploid_pinf_cc, replen = c(2, 2, 2, 3, 3, 2, 2, 2, 2, 2, 2), add = TRUE, loss = TRUE, showplot = FALSE, include.ties = TRUE)

set.seed(999)
plot_poppr_msn(diploid_pinf_cc,
               min_span_net,
               inds = "NONE",
               mlg = FALSE,
               gadj = 9,
               nodebase = 1.15,
               palette = rainbow,
               cutoff = NULL,
               quantiles = FALSE,
               beforecut = TRUE,
               layfun = igraph::layout.auto)



```


## Hexp vs altitude
```{r}

alt_data <- read.csv("GST_altitude.csv")
class(alt_data)

ggplot(data = alt_data, aes(x = Altitude, y = Hexp)) + geom_point()

ln_reg <- lm(Hexp ~ Altitude, data = alt_data)
summary(ln_reg)


```








